### ISSUE TITLE
Documentation for Secrets missing a step

### ISSUE THREAD

**Issue by TejjeT** [awsdocs/amazon-ecs-developer-guide#110]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-tutorial.html
The above page is missing the `ECS_ENABLE_AWSLOGS_EXECUTIONROLE_OVERRIDE=true` as part of EC2 bootstrap. Without this step we are getting the following error

STOPPED (Fetching secret data from AWS Secrets Manager in region us-east-1: secret arn:aws:secretsmanager:us-east-1:<Acctnumber>:secret:secretname-1aBCDe: RequestError: send request failed caused by: Post https://secretsmanager.us-east-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-east-1.amazonaws.com on 10.7.166.253:53: no such host)

we are able to pull secrets successfully by adding ECS_ENABLE_AWSLOGS_EXECUTIONROLE_OVERRIDE=true to bootstrap.

**Comment by joelbrandenburg** [comment]
Are you using a Linux or Windows-based EC2 instance with your tasks?
