### ISSUE TITLE
Exposing multiple ports on one ECS Service

### ISSUE THREAD

**Issue by MichaelSmyth0184** [awsdocs/amazon-ecs-developer-guide#124]
Hi,
I have followed multiple links online around ECS service having multiple Target groups but I cannot seem to get this working. I have also noticed when using the AWS Web Interface that it is not possible to add multiple target groups to a service and only allows one.

![image](https://user-images.githubusercontent.com/34038292/82694207-c7206480-9c5a-11ea-8564-2ff99ee390cf.png)

Can anyone explain this? Would be greatly appreciated, as I can only seem to be able to serve one port behind a load balancer for the same service.

**Comment by joelbrandenburg** [comment]
The console doesn't support this at this time but this documentation shows how to do this within your service definition file:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html
