### ISSUE TITLE
where is the documentation for firelensConfiguration which should be part of task definition parameter

### ISSUE THREAD

**Issue by tkumark** [awsdocs/amazon-ecs-developer-guide#130]
in this page https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_storage I do not see any information on **firelensConfiguration** parameter 

```
    {
      "essential": true,
      "image": "amazon/aws-for-fluent-bit:latest",
      "name": "log_router",
      "firelensConfiguration": {
        "type": "fluentbit",
        "options": {
          "enable-ecs-log-metadata": "true"
        }
      },
      "memory": 128
    }
```

![image](https://user-images.githubusercontent.com/2689801/84615008-609f0700-aee5-11ea-8264-20ddee60c867.png)

**Comment by joelbrandenburg** [comment]
You can read about that here:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html

I'll also update the task definition parameters page as it should be there as well.

**Comment by joelbrandenburg** [comment]
I've added it to the task definition parameters page as well, here:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_storage
