### ISSUE TITLE
using_awslogs - non-blocking mode

### ISSUE THREAD

**Issue by henriquesantanati** [awsdocs/amazon-ecs-developer-guide#133]
Add the  option "non-blocking" and "max-buffer-size" as an ["Available awslogs Log Driver Options"](https://github.com/awsdocs/amazon-ecs-developer-guide/blob/295a968cf5b385e66f95c90c84651566d25c8119/doc_source/using_awslogs.md#available-awslogs-log-driver-options).

Please find here the further information about this option: 

[Allow awslogs to use non-blocking mode ](https://github.com/moby/moby/pull/36522/commits/c7e379988c9cd6ec0af528e6f59eea3c51b36738)
[Configure the delivery mode of log messages from container to log driver](https://docs.docker.com/config/containers/logging/configure/#configure-the-delivery-mode-of-log-messages-from-container-to-log-driver)

**Comment by joelbrandenburg** [comment]
Both of these have been added to the documentation here:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html#create_awslogs_logdriver_options

**Comment by henriquesantanati** [comment]
Hi joelbrandenburg,

I can see that this option was removed from the docs. Do you know why?

Thanks

**Comment by joelbrandenburg** [comment]
Thanks for bringing this to my attention.  It looks like that change was reverted inadvertently so I am publishing a change to fix this.
