### ISSUE TITLE
Using Amazon ECS Parameters - Outdated

### ISSUE THREAD

**Issue by henriquesantanati** [awsdocs/amazon-ecs-developer-guide#142]
According the [public documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-ecsparams.html), there is no `depends_on` parameter. 

But, as you can see on the [AWS CLI repository](https://github.com/aws/amazon-ecs-cli/blob/mainline/README.md#using-ecs-parameters), it exists.

Can you please update the public documentation with the latest  ecs-params.yml parameters?

Thanks in advance

**Comment by henriquesantanati** [comment]
It seams that the `depends_on` is not working. Probably this is the reason that the doc wasn't updated yet. 

Just to let you know before update the doc.

**Comment by joelbrandenburg** [comment]
Yeah, so the dependsOn parameter exists within the Amazon ECS API but the ECS CLI does not support it yet.  Once the ECS CLI supports that particular feature we will update the documentation.
