### ISSUE TITLE
Missing word in Getting Started sentence

### ISSUE THREAD

**Issue by adityamenon** [awsdocs/amazon-ecs-developer-guide#145]
Happy new year 2021, dear reader!

In the [getting started page](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/Welcome.html#welcome-getstarted), the following line is incomplete / missing the intended word & hyperlink:

`To learn about the developer tools available for using Amazon ECS, see .`

There should be a word & hyperlink after `see`, above.

**Comment by joelbrandenburg** [comment]
Thanks for pointing this out, the documentation has been updated.
