### ISSUE TITLE
Fix wording on LATEST for Fargate Platform version

### ISSUE THREAD

**Issue by saiteja313** [awsdocs/amazon-ecs-developer-guide#146]
As per ECS User guide, 

Fargate Platform version as per [platform_versions.html](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html) documentation refers 1.4.0 as LATEST version.

However, when launching a Fargate task for ECS, LATEST refers to 1.3.0.

Raising this issue to fix wording in documentation.

**Comment by joelbrandenburg** [comment]
Yes, I have made the changes to clear up that the LATEST platform version is still pointing to 1.3.0.  Thanks!
