### ISSUE TITLE
Inconsistency in list of supported Windows ECS-optimized AMIs

### ISSUE THREAD

**Issue by Nikita-T86** [awsdocs/amazon-ecs-developer-guide#148]
On this page https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html the list of supported AMIs contains "Amazon ECS-optimized Windows Server **2004** Core AMI", but on this page https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows.html the list doesn't contain it, only older ones like 1909 and 2019.

**Comment by joelbrandenburg** [comment]
Thanks for pointing this out.  The documentation has been updated.
