### ISSUE TITLE
Installing ECS CLI on Windows 

### ISSUE THREAD

**Issue by fjpa121197** [awsdocs/amazon-ecs-developer-guide#158]
Hello, Im having trouble understanding the "Installing the Amazon ECS CLI" guide. Im trying to install it on Windows machine. However, when I run this command in Powersheel as administrator:
`gpg --keyserver hkp://keys.gnupg.net --recv BCE9D9A42D51784F`

My ouput is the following:
```
gpg: requesting key 2D51784F from hkp server keys.gnupg.net
gpg: key 2D51784F: "Amazon ECS <ecs-security@amazon.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

But for the follwing command:
`gpg --import <public_key_filename>`

I cannot find any `public_key_file_Name ` to use in the import statement. I have also try creating it and place in the same directory (I copy paste the content that is the guide into a file and save it as .gpg, and then I place the file in the same directory). However, when I try to import it, the following message pops up:
My command: `gpg --import aws-ecs-cli-gpg.gpg`
Output:
```
gpg: can't open `aws-ecs-cli-gpg.gpg': No such file or directory
gpg: Total number processed: 0
```
But I dont know why it says that there is no such file or directory, when I cann clearly see the file in the explorer. 

Can anyone help me please? I have been stuck with this over the past days.

**Comment by joelbrandenburg** [comment]
Thanks for taking the time to submit feedback on our documentation.  It sounds like you actually have a technical support question.  I suggest that you post it on AWS re:Post, which is a good resource for questions and answers: https://repost.aws

You might also consider signing up for AWS technical support: https://aws.amazon.com/premiumsupport/
