### ISSUE TITLE
Capacity Provider UPDATE_FAILED.  Any options for finding out more information?

### ISSUE THREAD

**Issue by darrenweiner** [awsdocs/amazon-ecs-developer-guide#160]
Change this to a feature request, as toggling the Managed Instance/Managed Termination flags to Disable then Enable seemed to then allow for the the update to TargetCapacity.
If a capacity provider update fails, need to provide details as to the problem. The current updateStatusReason: referencing a client exception and documentation that does not exist, is not helpful at all...e.g.
            "updateStatus": "UPDATE_FAILED",
            "updateStatusReason": "The capacity provider can't be updated right now due to a client exception. See the documentation for possible causes or wait and try again.",
(this is an autoScalingGroupProvider cp).

Reason should provide a greater level of detail as to the cause, not reference 'the documentation'

**Comment by joelbrandenburg** [comment]
I've submitted this feedback internally to the team.  For future reference, feature requests can be added to the containers roadmap here: https://github.com/aws/containers-roadmap/issues
