### ISSUE TITLE
Fargate bind-mounts example

### ISSUE THREAD

**Issue by henriquesantanati** [awsdocs/amazon-ecs-developer-guide#164]
Looking at the [bind-mount](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html) documentation, I've seen this example: **To mount volumes from another container using volumesFrom**. 

This example will work well with EC2 launch type. But, for Fargate 1.4, the containers will not be able to see the files written by the other container.

In order to do so, both containers should use the same volume instead of one of them (in case of 2 containers) uses the volumes_from directive. 

I was able to reproduce the issue and put it working fine after modify my task definition to use the same `volumes` for both containers instead of use the `volumesFrom`.

Let me know if you have any questions.

**Comment by joelbrandenburg** [comment]
Using the volumesFrom parameter with tasks hosted on Fargate works, you just have to be mindful of the VOLUME directive in the Dockerfile.  We have a note to this effect in the docs under the list of considerations.  See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html#bind-mount-considerations

Reopen this issue if you don't feel this resolves your issue. Thanks!
