### ISSUE TITLE
ECS System Parameter Store Cross Account Alert

### ISSUE THREAD

**Issue by timothyaws** [awsdocs/amazon-ecs-developer-guide#167]
When trying to add a cross account parameter into a task definition, ECS errors out with

`The Systems Manager parameter ARN has a different account ID than the current account. The current account ID is ********* and the ARN account ID is ***********. Cross-account access for ARNs is not currently supported.`

However, the documentation does not make it clear that Cross-account access via ARNs is not supported in the documentation. 

This should be listed as a consideration to make this clear.

**Comment by joelbrandenburg** [comment]
We are adding a note to this effect in the documentation.  Thanks for bringing this to our attention.
