### ISSUE TITLE
ECS AMI SNS Notifications Update

### ISSUE THREAD

**Issue by v4de** [awsdocs/amazon-ecs-developer-guide#184]
I noticed the documentation for subscribing to the ECS optimized AMI updates was deleted 11 days ago and is now found under windows ami section.

/doc_source/ECS-AMI-SubscribeTopic.md

https://github.com/awsdocs/amazon-ecs-developer-guide/commit/1114647d1722fdb796cea68f680b00e19439fbbd#diff-6c7023cf1cbe5e3fd7cab63759b1980ced42646344daaade4393ea7023cf267f

Is there another option for being notified of ecs optimized linux 2 ami updates?

**Comment by joelbrandenburg** [comment]
The SNS notification ARN for the Linux AMI was deprecated when the Amazon ECS-optimized Linux AMI was deprecated.  For the Linux variant AMIs there was never separate SNS topics for each variant, it was all tied to the Amazon Linux AMI.  The team creates separate SSM Parameter Store parameters for each variant so each one can be queried at any point to retrieve the latest AMI ID.  You can view those here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html

There isn't any notification system to notify when a new AMI is released for Linux.
