### ISSUE TITLE
Allocate GPU with new ECS console

### ISSUE THREAD

**Issue by biyer19** [awsdocs/amazon-ecs-developer-guide#191]
For tasks hosted on Amazon EC2, how do you specify the GPUs that should be allocated for the task/container?

**Comment by joelbrandenburg** [comment]
At the current time, you can use the Amazon ECS "classic" console to add GPU requirements for your containers.  When registering a new task definition, when you add your container definitions, underneath the "Environment" section there is a field for GPUs.  This functionality hasn't been added to the ECS new console experience yet.  You can find more details on https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-gpu.html#ecs-gpu-specifying
