### ISSUE TITLE
Unable to create Task definition

### ISSUE THREAD

**Issue by berry2012** [awsdocs/amazon-ecs-developer-guide#196]
While following tutorial steps to create FSx with ECS. 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/tutorial-wfsx-volumes.html#wfsx-create-instance
Encountered error below when carrying out step 6.
Step 6: Paste the following sample task definition JSON into the text area (replacing the pre-populated JSON there) and choose Save.

<img width="1405" alt="Screenshot 2022-02-21 at 17 05 44" src="https://user-images.githubusercontent.com/10167641/155007617-b59daa37-f90d-4534-b829-f9f9ac5d1913.png">

**Comment by joelbrandenburg** [comment]
In addition to the changes you've made with your commits, the task execution IAM role is also required so I'll be adding that to the task definition example we provide in the docs.  Other than that, the steps in the doc appear to work for me.  Reopen this issue if you have further issues.
