### ISSUE TITLE
Help Wanted – Troubleshooting, Tips, and Tricks

### ISSUE THREAD

**Issue by joelbrandenburg** [awsdocs/amazon-ecs-developer-guide#20]
Please share your experience! If you've hit a problem and solved it, I’d love to hear from you. I am also interested in any tips or tricks you’ve learned along the way.

Submit a pull request (instructions [here](https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/CONTRIBUTING.md)) or send me a note via the Comments below. If your suggestion is likely to help others, I'll add it to the Amazon ECS Developer Guide.

Thank you for your time. I look forward to hearing from you!

**Comment by fjpa121197** [comment]
Hello, Im having trouble understanding the "Installing the Amazon ECS CLI" guide. Im trying to install it on Windows machine. However, when I run this command in Powersheel as administrator:
`gpg --keyserver hkp://keys.gnupg.net --recv BCE9D9A42D51784F`

My ouput is the following:
```
gpg: requesting key 2D51784F from hkp server keys.gnupg.net
gpg: key 2D51784F: "Amazon ECS <ecs-security@amazon.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

But for the follwing command:
`gpg --import <public_key_filename>`

I cannot find any `public_key_file_Name ` to use in the import statement. I have also try creating it and place in the same directory (I copy paste the content that is the guide into a file and save it as .gpg, and then I place the file in the same directory). However, when I try to import it, the following message pops up:
My command: `gpg --import aws-ecs-cli-gpg.gpg`
Output:
```
gpg: can't open `aws-ecs-cli-gpg.gpg': No such file or directory
gpg: Total number processed: 0
```
But I dont know why it says that there is no such file or directory, when I cann clearly see the file in the explorer. 

Can anyone help me please? I have been stuck with this over the past days.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
