### ISSUE TITLE
ECS Fargate Task Definition nofile hard limit - Ulimit Inconsistency

### ISSUE THREAD

**Issue by magreenbaum** [awsdocs/amazon-ecs-developer-guide#201]
Looking at the following docs, the nofile hard limit default is stated to be `1048576`. 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-resource-limits

This limit conflicts with the following doc (states hard limit default is `4096`):
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Ulimit.html

Running `ulimit -a -H` via ecs exec in a container with no ulimit parameters in the task definition shows `4096`.

**Comment by browndjaz** [comment]
HI,

Thanks for the feedback. The correct value is 4096.  I have updated the documentation to reflect this value. The docs are on the public site and github,

Thanks
