### ISSUE TITLE
Help Wanted - Example Task Definitions

### ISSUE THREAD

**Issue by joelbrandenburg** [awsdocs/amazon-ecs-developer-guide#21]
Please share your example task definitions! If you have a useful or interesting task definition example that you feel other users could benefit from, let us know.

Submit a pull request (instructions [here](https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/CONTRIBUTING.md)) or send me a note via the Comments below. If your suggestion is likely to help others, I'll add it to the list of example task definitions [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_task_definitions.html) in the Amazon ECS Developer Guide.

Thank you for your time. I look forward to hearing from you!

**Comment by NeerajaPotluri** [comment]
Is there a task definition parameter to control this behavior "Whether the task should continue to run if the container finishes or fails" - Couldn't find how to set it. Any help or suggestion is appreciated

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
