### ISSUE TITLE
task_definition_parameters.md has some error

### ISSUE THREAD

**Issue by yiyu0x** [awsdocs/amazon-ecs-developer-guide#215]
In task_definition_parameters.md, the Environment section in task_definition_parameters.md may have some errors

because the context below it is in containerDefinitions in the container's JSON file 

so I have no idea why the section was named Environment

**Comment by joelbrandenburg** [comment]
The section headings we use, such as "Environment", are based on the same labels in the Amazon ECS classic console. As the team continues to develop the new Amazon ECS console experience, we will reorganize the task definition parameter list accordingly.  If you have any suggestions for the way we organize the parameters, please let us know.
