### ISSUE TITLE
Typo error in the ECS documentation

### ISSUE THREAD

**Issue by Sunny-Gajjar** [awsdocs/amazon-ecs-developer-guide#239]
Hi,

I've noted a typo error here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-definition-state.html 
In line number(13); I know it's a minor change though significant to make an improvement and therefore I've  raised a PR for correction. 

PR Reference: https://github.com/awsdocs/amazon-ecs-developer-guide/pull/238
---

Current state at line(13): "Task definitions that are in **he** DELETE_IN_PROGRESS*"
Correction at line (13): "Task definitions that are in **the** DELETE_IN_PROGRESS *"

---

Request you to please review and update the document.

Thanks,
Sunny Bhadesiya

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
