### ISSUE TITLE
service definition parameters is missing info about serviceRegistries

### ISSUE THREAD

**Issue by sihaya** [awsdocs/amazon-ecs-developer-guide#24]
The service documentation (service_definition_parameters.md) seems to be missing information about the serviceRegistries attribute. 

This attribute instructs ECS to register an instance with a servicediscovery service whenever a task is created or destroyed. The tutorial about service discovery (service-discovery.md) does contain this attribute and it is actually working.

**Comment by joelbrandenburg** [comment]
This issue is fixed in the latest docs.
