### ISSUE TITLE
setting ecs endpoints for AWS Batch on Fargate

### ISSUE THREAD

**Issue by shekars194** [awsdocs/amazon-ecs-developer-guide#241]
Do I need to setup the three ecs endpoints when using AWS Batch with FARGATE? It is needed when I am using AWS Batch with ec2. when setting up the ecs endpoints resources needs to be "*" which is not allowed in our firm. Can I skip setting up this endpoints if I switch to AWS Batch on FARGATE.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
