### ISSUE TITLE
Confusion in task definiton parameter cpu

### ISSUE THREAD

**Issue by fbukevin** [awsdocs/amazon-ecs-developer-guide#5]
In the page of Task Definition Parameters, there are two confusion statements I would request a further explanation or clarify.

https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/doc_source/task_definition_parameters.md#

**Line 196**
> **Agent versions <= 1.1.0:** Null and zero CPU values are passed to Docker as 0, which Docker then converts to 1,024 CPU shares. CPU values of 1 are passed to Docker as 1, which the Linux kernel converts to 2 CPU shares.

Here the document says:
1. Null and zero CPU values are passed to Docker as 0, which **Docker** then converts to 1,024 CPU shares.
2. CPU values of 1 are passed to Docker as 1, which the **Linux kernel** converts to 2 CPU shares.

Does that means when user set the value to 0 and 1(or larger), the conversion will be done by Docker and Linux kernel respectively? Or, the second one should be "Docker" as well? 

**Line 197**
>  **Agent versions >= 1.2.0:** Null, zero, and CPU values of 1 are passed to Docker as 2.

Dose the unit of 2 is CPU shares?

**Comment by nrdlngr** [comment]
For line 196, null, zero, and 1 CPU shares in a task definition were treated as special cases for the reasons explained here. Docker would convert null and zero values to 1,024, and the Linux kernel converted a CPU share of 1 into 2 CPU shares. Keep in mind that the 1.1.0 version of the agent is very old (released almost 3 years ago); if you are still using that version of the agent, you should upgrade your container instances.

For line 197, yes, that should say 2 CPU shares. I'll make that clarification. Thanks for your feedback.

**Comment by nrdlngr** [comment]
I've updated the CPU share text to address the feedback in this issue.
