### ISSUE TITLE
Update documentation for Amazon Linux 2

### ISSUE THREAD

**Issue by nbrys** [awsdocs/amazon-ecs-developer-guide#51]
https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/doc_source/using_cloudwatch_logs.md

This page (end especially the script at the bottom of the page) is for amazon linux but not for amazon linux 2. Please update this page so every works with amazon linux 2

**Comment by joelbrandenburg** [comment]
We have added scripts for both Amazon Linus and Amazon Linux 2.  Thanks for your feedback!

**Comment by nrdlngr** [comment]
Thanks for reporting this. We're looking into it now. I'll respond here when we have more information.

**Comment by joelbrandenburg** [comment]
We've included an updated script for Amazon Linux 2.  https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/doc_source/using_cloudwatch_logs.md
