### ISSUE TITLE
Misleading information about Bind mounts support for AWS Fargate

### ISSUE THREAD

**Issue by dkovvuri** [awsdocs/amazon-ecs-developer-guide#56]
AWS Documentation states that AWS Fargate supports mounting Host Volumes - which is not supported [1] . From my understanding, Fargate Supports mounting other Docker Volumes by using the 'volumesFrom' property. But doesn't inherently support Bind Mounts. 

There are multiple citations of this error - which need to be corrected. 

Citation 1: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html
Citation 2: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html

Reference:

[1] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html

**Comment by joelbrandenburg** [comment]
AWS Fargate supports nonpersistent bind mount volumes.  The 'host' and 'sourcePath' fields aren't supported.
