### ISSUE TITLE
Fix typo `&lt;&lt;` in User data example of page `Launching an Amazon ECS Container Instance`

### ISSUE THREAD

**Issue by dwchiang** [awsdocs/amazon-ecs-developer-guide#60]
One example shows `cat &lt;&lt;'EOF' >> /etc/ecs/ecs.config` which should be `cat <<'EOF' >> /etc/ecs/ecs.config`. Would like to fix it to avoid reader miss configuration.

**Comment by joelbrandenburg** [comment]
Thanks for your contribution, this has been added to the documentation.
