### ISSUE TITLE
Documentation doesn't say what to do what imagedefinitions.json

### ISSUE THREAD

**Issue by talolard** [awsdocs/amazon-ecs-developer-guide#65]
Hi,
I've been going through the example of setting up a codepipeline that deploys to fargate. 
Reading through the [tutorial](https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/doc_source/ecs-cd-pipeline.md) there is a detail missing or unclear. 

During the build phase, we create an imagedefinitions.json file, but it's not clear how to reference it during the codepipeline stage. E.g. where is that artifact and how will codepipeline know that ? 

Thanks

**Comment by joelbrandenburg** [comment]
This tutorial was moved over to the CodePipeline documentation a while back.  If this is still an issue, let me know.
https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html
