### ISSUE TITLE
Code Snippet syntax error

### ISSUE THREAD

**Issue by kimhyunchae91** [awsdocs/amazon-ecs-developer-guide#70]
The code snippet which contains task definition where two containers are sharing a single volume is NOT separated by a comma. I tried to contact someone via AWS forums but not responsive at all.
![fargate-error](https://user-images.githubusercontent.com/25262401/57957379-ebf83400-78b0-11e9-9ac6-b9546734427d.PNG)

**Comment by joelbrandenburg** [comment]
Thanks for pointing out this typo.  We will publish a fix later today.  Thanks for using Amazon ECS!
