### ISSUE TITLE
Service Discovery considerations suggestion

### ISSUE THREAD

**Issue by dkeightley** [awsdocs/amazon-ecs-developer-guide#79]
Hi team,

I wanted to suggest that the considerations could be bolstered to include a note that for resolution to be successful the Amazon Provided DNS must be used for resolution of the DNS names.

But also `enableDnsHostnames`, and not just `enableDnsSupport` must be `true` on the VPC configuration for custom Private hosted zones to be resolvable - as covered here: 

https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-support

**Comment by browndjaz** [comment]
Hi,

Thanks for the suggestion. I will add the information into the documentation.
