### ISSUE TITLE
ECS service auto scaling in BJS

### ISSUE THREAD

**Issue by gavinkou2018** [awsdocs/amazon-ecs-developer-guide#8]
The document says that:
"Service Auto Scaling is not currently available in the ECS console in the following regions: 
China (Beijing) | cn-north-1"

However, Service Auto Scaling is actually available in the ECS console in BJS.

See the attached file for the screenshot of the console:
<img width="876" alt="screen shot 2018-04-10 at 10 40 36" src="https://user-images.githubusercontent.com/38234835/38533393-a93d65dc-3cab-11e8-8f7f-eb6b8237afb0.png">

**Comment by nrdlngr** [comment]
Thanks for catching this. I've confirmed that Service Auto Scaling is available in the cn-north-1 region, and I've removed the note stating otherwise.
