### ISSUE TITLE
startTimeout and stopTimeout need units - milliseconds, seconds, minutes?

### ISSUE THREAD

**Issue by ORESoftware** [awsdocs/amazon-ecs-developer-guide#80]
If you look here:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-user

> StopTimeout
> Time duration to wait before the container is forcefully killed if it doesn't exit normally on its own. 

It doesn't tell us the units, I assume milliseconds, but it's pretty unclear, also for startTimeout.

**Comment by joelbrandenburg** [comment]
The unit is seconds for both startTimeout and stopTimeout.  We are pushing out an update to the documentation to make this clear.  Thanks for bringing this to our attention!

**Comment by ORESoftware** [comment]
np, ty tbh it was very unclear, I was in fact off by a factor of 1000 lulz
