### ISSUE TITLE
Steps for enabling IAM roles in Windows container unclear

### ISSUE THREAD

**Issue by Kralizek** [awsdocs/amazon-ecs-developer-guide#93]
In [this page of the documentation](https://docs.aws.amazon.com/en_pv/AmazonECS/latest/developerguide/windows_task_IAM_roles.html), it would be nice to have concrete examples on how to set up your containers so to execute the bootstrap script when a container starts.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
